fbc64 -i ../include -p ../lib/win64 -w all -exx -g 2d_camera_platformer.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g 2d_camera_split_screen.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g 2d_camera.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g 3d_camera_first_person.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g 3d_camera_free.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g 3d_camera_mode.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g 3d_camera_split_screen.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g 3d_picking.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g basic_screen_manager.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g basic.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g bullet_hell.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g delta_time.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g input_gamepad_info.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g kaleidoscope.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g raygui_control_test_suite.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g raygui_simple.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g shaders_basic_lighting.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g scissor_test.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g smooth_pixel_perfect.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g models_first_person_maze.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g models_animation.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g models_billboard.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g models_box_collisions.bas
fbc64 -i ../include -p ../lib/win64 -w all -exx -g models_bone_socket.bas